### ISSUE TITLE
秦哥，能做到步频模拟吗

### ISSUE THREAD

**Issue by YanSGod** [Amorter/HenuRun#1]
哥们今天自己肉身跑都步频不合格，真破防了

![QQ图片20231016203830](https://github.com/Amorter/HenuRun/assets/99068464/7e0b8764-415b-40c6-a1d2-8f78d2ee033a)

**Comment by Amorter** [comment]
可以的，已经集成进代码了，可以直接运行

**Comment by Mirtrn** [comment]
哥们能不能适用于其他app的步频模拟，
