### ISSUE TITLE
雷电的date文件夹里没别的了，要自己创建文件夹吗

### ISSUE THREAD

**Issue by YanSGod** [Amorter/HenuRun#3]
![image](https://github.com/Amorter/HenuRun/assets/99068464/12466834-83a8-4d77-bed3-dd6481abf8c4)

**Comment by Amorter** [comment]
你有启动过模拟器吗，启动一下模拟器再看看

**Comment by YanSGod** [comment]
> 你有启动过模拟器吗，启动一下模拟器再看看

试过了真没，你能重新安装下看看目录吗
![image](https://github.com/Amorter/HenuRun/assets/99068464/eaeb3935-529a-4339-917c-d3b2573a71b8)

**Comment by Amorter** [comment]
那俩程序就在你这个安装目录下面，不是data目录下。就是你这个目录的ld.exe和ldconsole.exe

**Comment by YanSGod** [comment]
怎么会是呢






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Amorter/HenuRun"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月17日(星期二) 晚上9:10
***@***.***&gt;;
抄送:&nbsp;" ***@***.******@***.***&gt;;
主题:&nbsp;Re: [Amorter/HenuRun] 雷电的date文件夹里没别的了，要自己创建文件夹吗 (Issue #3)





 
那俩程序就在你这个安装目录下面，不是data目录下。就是你这个目录的ld.exe和ldconsole.exe

**Comment by YanSGod** [comment]
1

**Comment by Amorter** [comment]
什么？

**Comment by YanSGod** [comment]
看我这篇邮件里的图片plz



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月17日(周二) 晚上10:47
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Amorter/HenuRun] 雷电的date文件夹里没别的了，要自己创建文件夹吗 (Issue #3)




 
什么？

**Comment by Amorter** [comment]
我看到了，我确实在你这个照片最下面看到了ld.exe

**Comment by YanSGod** [comment]
那这个报错是啥🦆



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月17日(周二) 晚上11:01
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Amorter/HenuRun] 雷电的date文件夹里没别的了，要自己创建文件夹吗 (Issue #3)




 
我看到了，我确实在你这个照片最下面看到了ld.exe

**Comment by Amorter** [comment]
我没有看到你的报错，你给下联系方式吧

**Comment by YanSGod** [comment]
Q.2908381275.之前在贴吧群加过你的😘



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月17日(周二) 晚上11:05
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Amorter/HenuRun] 雷电的date文件夹里没别的了，要自己创建文件夹吗 (Issue #3)




 
我没有看到你的报错，你给下联系方式吧
